version: 0.1

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 339095555060.dkr.ecr.ap-south-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t manoj99 .
      - docker tag manoj99:latest 339095555060.dkr.ecr.ap-south-1.amazonaws.com/manoj99:latest      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 339095555060.dkr.ecr.ap-south-1.amazonaws.com/manoj99:latest
      - envsubst < "fargate.template.json" > "fargate.json"
artifacts:
  files:
    - 'fargate.json'
  name: $IMAGE_TAG
